version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qnr63363

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/stock_image_sharing_platform
    ports:
      - "8000:8000"
    depends_on:
      - db