# Generated by Django 3.2.15 on 2022-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
