# Generated by Django 3.2.15 on 2022-09-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_alter_images_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='user_Id',
            new_name='user',
        ),
    ]
