# Generated by Django 3.2.15 on 2022-09-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_rename_user_id_images_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image_category',
            old_name='images_id',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='role_permission',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='role_permission',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='user_id',
            new_name='user',
        ),
    ]
