# Generated by Django 3.2.15 on 2022-09-08 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_auto_20220905_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
