# Generated by Django 3.2.15 on 2022-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_auto_20220918_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='location',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
