# Generated by Django 3.2.15 on 2022-09-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_like_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='timestamp',
        ),
    ]
