# Generated by Django 3.2.15 on 2022-10-02 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0009_remove_like_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
