# Generated by Django 3.2.15 on 2022-10-07 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0011_alter_categories_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_app.images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', through='stock_app.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
