# Generated by Django 3.2.15 on 2022-10-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_auto_20221007_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Images',
            field=models.ManyToManyField(blank=True, default=None, related_name='image_categories', through='stock_app.Image_category', to='stock_app.Images'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('image', 'user')},
        ),
    ]
